package network;

public enum CommandType {
    PING,

    CHUCVU_LOAD_ALL,

    KHACHHANG_FIND_BY_ID,
    KHACHHANG_LOAD_ALL,
    KHACHHANG_SEARCH,
    KHACHHANG_SAVE,
    KHACHHANG_UPDATE,
    KHACHHANG_DELETE,

    NHANVIEN_FIND_BY_ID,
    NHANVIEN_LOAD_ALL,
    NHANVIEN_SEARCH,
    NHANVIEN_SAVE,
    NHANVIEN_UPDATE,
    NHANVIEN_DELETE,

    TAIKHOAN_FIND_BY_ID,
    TAIKHOAN_LOAD_ALL,
    TAIKHOAN_SEARCH,
    TAIKHOAN_UPDATE,
    TAIKHOAN_DELETE,
    TAIKHOAN_RESET_PASSWORD,

    KHUYENMAI_FIND_BY_ID,
    KHUYENMAI_LOAD_ALL,
    KHUYENMAI_SEARCH,
    KHUYENMAI_SAVE,
    KHUYENMAI_UPDATE,
    KHUYENMAI_DELETE,

    THONGKE_DOANHTHU,
    THONGKE_TOP_KHACH_HANG,
    THONGKE_TOP_SAN_PHAM
}